* Citizen Monitoring Hub

** About
TODO

** To Install:
This application is being developed on Ubuntu, though it may be possible to install / run this on Windows/ MacOS.

** Dependencies:
 + Django v1.3 or later (http://djangoproject.com)
 + South v0.7.1 or later (http://aeracode.com or sudo easy_install South)
 + PostgreSQL v8.4
 + xlrd (sudo easy_install xlrd)
 + python-psycopg2 (sudo apt-get install python-psycopg2)

** Steps:
 + Ensure that the user required by PostgreSQL is created on your system (Do not use the default username provided in default settings.py)
 + Create the PostgreSQL database as specified by settings.

 The application depends on an environment variable. For running this application on your development machine, use your shell's mechanisms to set the following environment variable:

 $ CMH_APP_DIR=<CitizenMonitoringHub Directory>/src

 Run the following commands

 + ./manage.py syncdb
 + ./manage.py migrate
 + ./manage.py init_roles
 + ./manage.py init_statuses
 + ./manage.py init_status_transition

 Beyond the above setup, the application requires locations, departments and complaint types. These can be separately initialized by a set of other scripts included with the application. Or the Application provided UI can be used for that purpose. The commands for this purpose are:
 + ./manage.py init_departments
 + ./manage.py init_locations
 + ./manage.py init_complaints

